version: 2

sources:
  - name: raw_data_circle_dbt
    description: raw data circle sportswear dataset for investigation
    tables:
      - name: raw_cc_stock
        description: stock of products
      - name: raw_cc_sales
        description: sales data of products


models:
  - name: stg_raw_data_circle_dbt__raw_cc_sales
    description: cleaning raw sales
  - name: stg_raw_data_circle_dbt__raw_cc_stock
    description: cleaning raw stock
  - name: int_stock_sales
    description: combination of stock and sales with selected columns